# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [16]:
import numpy as np

arr1 = np.random.randint(1, 21, size=(5,5))
print("Original array \n")
print(arr1)

print("\n Modified array \n")
arr1[:,2] = 1
print(arr1)

Original array 

[[13  5  7  3  3]
 [16 17  4  5 18]
 [14 15 11 20  1]
 [ 8  7 16 10 20]
 [ 5 10 19  9  1]]

 Modified array 

[[13  5  1  3  3]
 [16 17  1  5 18]
 [14 15  1 20  1]
 [ 8  7  1 10 20]
 [ 5 10  1  9  1]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [10]:
import numpy as np
arr2 = np.arange(1, 17).reshape((4, 4))
print("The original matrix : ")
print(arr2, " ")

print("Thw modified matrix : ")
np.fill_diagonal(arr2, 0)
print(arr2)

The original matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]  
Thw modified matrix : 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [13]:
import numpy as np

arr = np.arange(1, 37).reshape((6, 6))
print("The original array : ")
print(arr)

sub = arr[2:5, 1:4]
print(sub)

The original array : 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [26]:
arr = np.random.randint(1, 9, size=(5, 5))
print("The original array \n")
print(arr)


border_element = np.concatenate((arr[0, :], arr[-1, :], arr[1: -1, 0], arr[1: -1, -1]))
print("The border elements in a array \n")
print(border_element)

The original array 

[[8 2 5 1 1]
 [5 1 5 3 6]
 [1 7 6 3 8]
 [3 3 2 5 5]
 [7 1 7 6 4]]
The border elements in a array 

[8 2 5 1 1 7 1 7 6 4 5 1 3 6 8 5]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [31]:
arr1 = np.arange(1, 13).reshape((3, 4))
arr2 = np.arange(13, 25).reshape((3, 4))

print(arr1)
print("\n")
print(arr2)

print("\nAddition :\n")
print(arr1+arr2)
print("\nSubtraction : \n")
print(arr1-arr2)
print("\nMultiplication : \n")
print(arr1*arr2)
print("\nDivision : \n")
print(arr1/arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Addition :

[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]

Subtraction : 

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

Multiplication : 

[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]

Division : 

[[0.07692308 0.14285714 0.2        0.25      ]
 [0.29411765 0.33333333 0.36842105 0.4       ]
 [0.42857143 0.45454545 0.47826087 0.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [33]:
arr = np.arange(1, 17).reshape((4, 4))
print(arr)

row_sum = np.sum(arr, axis=1)
col_sum = np.sum(arr, axis=0)

print("\nThe row wise addition : \n")
print(row_sum)

print("\nThe row wise addition : \n")
print(col_sum)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The row wise addition : 

[10 26 42 58]

The row wise addition : 

[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [36]:
arr = np.random.randint(1, 9, size=(5, 5))
print(arr)

print(f"The mean of the data : {np.mean(arr)}")
print(f"The standard deviation of the data : {np.std(arr)}")
print(f"The median of the data : {np.median(arr)}")
print(f"The variance of the data : {np.var(arr)}")

[[5 5 2 8 6]
 [4 1 8 7 1]
 [7 7 2 2 6]
 [6 3 4 2 8]
 [7 8 4 8 2]]
The mean of the data : 4.92
The standard deviation of the data : 2.431789464571306
The median of the data : 5.0
The variance of the data : 5.9136


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [42]:
data = np.arange(1, 10).reshape((3, 3))
print(data)

data_mean = np.mean(data)
data_std = np.std(data)

normi = (data - data_mean)/data_std
print("\nNormalize Data : \n")
print(normi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalize Data : 

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [45]:
arr = np.random.randint(1, 10, size=(3, 3))
row = np.random.randint(1, 6, size=(3,))

print("\nOriginal array:\n")
print(arr)
print("\n1D array:\n")
print(row)

result = arr+row
print("\nResulting array:\n")
print(result)


Original array:

[[4 2 4]
 [7 4 6]
 [7 2 1]]

1D array:

[1 4 3]

Resulting array:

[[5 6 7]
 [8 8 9]
 [8 6 4]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [47]:
arr = np.random.randint(1, 9, size=(4, 4))
row = np.random.randint(1, 6, size=(4,))

print("\nOriginal array:\n")
print(arr)
print("\n1D array:\n")
print(row)

result = arr-row
print("\nResulting array:\n")
print(result)


Original array:

[[2 4 2 6]
 [4 8 5 2]
 [3 2 5 2]
 [6 1 1 4]]

1D array:

[4 4 3 5]

Resulting array:

[[-2  0 -1  1]
 [ 0  4  2 -3]
 [-1 -2  2 -3]
 [ 2 -3 -2 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [51]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

print(f"The determinant of the matrix : {np.linalg.det(matrix)}")
print("The Inverse of the matrix :")
print(np.linalg.inv(matrix))
print(f"The eigenvalue of the matrix : {np.linalg.eigvals(matrix)}")

Original matrix:
[[ 8  7 10]
 [ 4  3  9]
 [ 7  5  6]]
The determinant of the matrix : 46.99999999999999
The Inverse of the matrix :
[[-0.57446809  0.17021277  0.70212766]
 [ 0.82978723 -0.46808511 -0.68085106]
 [-0.0212766   0.19148936 -0.08510638]]
The eigenvalue of the matrix : [19.79708312+0.j         -1.39854156+0.64665958j -1.39854156-0.64665958j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [52]:
arr1 = np.random.randint(1, 11, size=(2, 3))
arr2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

multi = np.dot(arr1, arr2)
print("The multiplication of the two matrix : ")
print(multi)

Array 1:
[[9 9 5]
 [7 4 1]]
Array 2:
[[1 1]
 [8 8]
 [8 4]]
The multiplication of the two matrix : 
[[121 101]
 [ 47  43]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [54]:
arr = np.arange(1, 10).reshape((3, 3))
print("Original array : ")
print(arr)

reshape_arr_1 = arr.reshape((1, 9))
print("The reshape array (1, 9) : ")
print(reshape_arr_1)

reshape_arr_2 = arr.reshape((9, 1))
print("The reshape array (9, 1) : ")
print(reshape_arr_2)

Original array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The reshape array (1, 9) : 
[[1 2 3 4 5 6 7 8 9]]
The reshape array (9, 1) : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [5]:
import numpy as np
arr = np.arange(1, 26).reshape((5, 5))
print("Original array : ")
print(arr)

Flat_array = arr.flatten()
print("\nFlattened array : \n")
print(Flat_array)

res = arr.reshape((5, 5))
print("\n Original shape : \n")
print(res)

Original array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Flattened array : 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

 Original shape : 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [9]:
arr = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(arr)

fancy_idx = arr[[0, 0, -1, -1], [0, -1, 0, -1]] 
print("Corners element : ")
print(fancy_idx)

Original array:
[[20 14 14 13]
 [13  5 10 17]
 [ 1 20 18  3]
 [14 15  4  2]]
Corners element : 
[20 13 14  2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [10]:
arr = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(arr)

arr[arr > 10] = 10
print("Modified element : ")
print(arr)

Original array:
[[ 4  3 10 15]
 [19 17 14 12]
 [ 5 11  9  5]
 [14  1  1 14]]
Modified element : 
[[ 4  3 10 10]
 [10 10 10 10]
 [ 5 10  9  5]
 [10  1  1 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [13]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Sahil', 25, 55.5), ('Manish', 30, 85.3), ('Pratyush', 20, 65.2), ('Manjit', 20, 65.2), ('Harsh', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted Array : ")
print(sorted_data)

Original array:
[('Sahil', 25, 55.5) ('Manish', 30, 85.3) ('Pratyush', 20, 65.2)
 ('Manjit', 20, 65.2) ('Harsh', 20, 65.2)]
Sorted Array : 
[('Harsh', 20, 65.2) ('Manjit', 20, 65.2) ('Pratyush', 20, 65.2)
 ('Sahil', 25, 55.5) ('Manish', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)], dtype=data_type)
print("Original array:")
print(data)

dist = 

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [18]:
import numpy.ma as ma
arr = np.random.randint(1, 17, size=(4, 4))
mask_arr = ma.masked_greater(arr, 10)
print("Original array : ")
print(arr)
print("Maked array : ")
print(mask_arr)

unmask_sum = mask_arr.sum()
print(f"The sum of unmasked arr : {unmask_sum}")

Original array : 
[[15 15  9 13]
 [ 4 10 13  5]
 [13 11 15  5]
 [14  6 13 11]]
Maked array : 
[[-- -- 9 --]
 [4 10 -- 5]
 [-- -- -- 5]
 [-- 6 -- --]]
The sum of unmasked arr : 39


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [23]:
import numpy.ma as ma
arr = np.random.randint(1, 17, size=(3, 3))
mask_arr = ma.masked_array(arr, mask=np.eye(3, dtype=bool))
print("Original matrix")
print(arr)
print("Masked Matrix : ")
print(mask_arr)

arr_mean = arr.mean()
masked = mask_arr.filled(arr_mean)
print("Modified Array : ")
print(masked)

Original matrix
[[11 15  1]
 [16 10 15]
 [ 6 13 13]]
Masked Matrix : 
[[-- 15 1]
 [16 -- 15]
 [6 13 --]]
Modified Array : 
[[11 15  1]
 [16 11 15]
 [ 6 13 11]]
