In [6]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.shape)

(5,)


In [11]:
arr1.reshape(1, 5)
arr1

array([1, 2, 3, 4, 5])

In [3]:
import numpy as np
arr = np.array([[1, 2, 3, 4,],[1, 2, 3, 4]])
print(arr)
print(arr.shape)
print(f"The size ofth array : {np.size(arr)}")

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)
The size ofth array : 8


In [7]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Vectorized operaton

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print(f"Addition : {arr1+arr2}")
print(f"Subtraction : {arr1-arr2}")
print(f"Multiplication : {arr1*arr2}")
print(f"Division : {arr1/arr2}")

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [7]:
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print(arr[0][0])

1


In [11]:
print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [14]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [15]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
